"""Initial models and business structure

Revision ID: ba817d092d4c
Revises: 19b4f410d0fb
Create Date: 2025-06-17 00:14:21.229326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba817d092d4c'
down_revision: Union[str, None] = '19b4f410d0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=True)
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    op.add_column('yape_transactions', sa.Column('business_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_yape_transactions_user_id'), table_name='yape_transactions')
    op.create_foreign_key(None, 'yape_transactions', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'yape_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yape_transactions', type_='foreignkey')
    op.drop_constraint(None, 'yape_transactions', type_='foreignkey')
    op.create_index(op.f('ix_yape_transactions_user_id'), 'yape_transactions', ['user_id'], unique=False)
    op.drop_column('yape_transactions', 'business_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'business_id')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
